# Cloudflare Pages設定ファイル
name = "cope-du"
compatibility_date = "2024-01-01"

# KVネームスペースのバインディング
[[kv_namespaces]]
binding = "NEWS_KV"
id = "YOUR_KV_NAMESPACE_ID"  # ← 後で実際のIDに置き換えてください
preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID"  # ← プレビュー用（オプション）

[build]
command = "npm run build"

